apiVersion: apps/v1
kind: Deployment
metadata:
  name: plasma-app-deployment
  labels:
    app: flasknode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasknode
  template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
      - name: flasknode
        image: icr.io/ibmsprint12/plasma
        imagePullPolicy: Always
        ports:
        - containerPort: 5000